apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
  labels:
    app: nodejs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: kubernetestest
          image: paal12345/nodejs-starter:6.15
          ports:
          - containerPort: 3000
          env:
          - name: LEADERELECTOR_SERVICE
            valueFrom:
              configMapKeyRef:
                name: kubernetest-configmap
                key: leaderelector_url
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  selector:
    app: nodejs
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: leaderelector-deployment
  labels:
    app: leaderelector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: leaderelector
  template:
    metadata:
      labels:
        app: leaderelector
    spec:
      containers:
        - name: kubernetestest
          image: paal12345/leaderelector:4.11
          ports:
          - containerPort: 3003
          env:
          - name: LEASE_TIME
            value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: leaderelector-service
spec:
  selector:
    app: leaderelector
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
